## SETUP file for Travis
## Make sure to rename the database name in the CREATE DATABASE script below to the SAME name as used for your local tests
---

dist: bionic

language: java

cache:
  directories:  
    - $HOME/.m2

script:
  - mvn test -e
  - mvn -Dremote.user=$REMOTE_USER -Dremote.password=$REMOTE_PW tomcat7:deploy

services:
   - mysql

before_script:
